import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import importPlugin from "eslint-plugin-import";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by Next on every build — editing it is pointless.
      "next-env.d.ts",
      // Vendored: the design system and the shared Zod contracts are owned
      // elsewhere (see AGENTS.md "Do not touch"), so linting them only
      // produces findings nobody here is allowed to act on.
      "src/vendor/**",
    ],
  },

  ...compat.extends("next/core-web-vitals", "next/typescript"),

  {
    plugins: { import: importPlugin },
    rules: {
      // `_name` is the established way here to say "destructured on purpose,
      // not used" — e.g. peeling prId off a mutation payload.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],

      /**
       * Architectural boundaries from the `frontend-ui-architecture` skill.
       * Dependencies point one way: shared → feature → route/app. Without this
       * rule the direction is only documentation, and sideways imports are
       * invisible in review because each one looks reasonable on its own.
       *
       * Starts at `warn` so the existing tree stays buildable; raise to `error`
       * once the current findings are cleared.
       */
      "import/no-restricted-paths": [
        "warn",
        {
          zones: [
            // Sibling route features may not reach into each other — lift the
            // shared part to src/components instead.
            { target: "./src/app/agents", from: "./src/app/repos" },
            { target: "./src/app/repos", from: "./src/app/agents" },
            { target: "./src/app/settings", from: "./src/app/repos" },
            { target: "./src/app/settings", from: "./src/app/agents" },
            { target: "./src/app/skills", from: "./src/app/agents" },
            { target: "./src/app/agents", from: "./src/app/skills" },
            { target: "./src/app/skills", from: "./src/app/repos" },
            { target: "./src/app/repos", from: "./src/app/skills" },

            // Nothing shared may depend on a feature; that inverts the arrow
            // and turns "shared" into a second copy of the app.
            { target: "./src/components", from: "./src/app" },
            { target: "./src/lib", from: "./src/app" },
            { target: "./src/lib", from: "./src/components" },
          ],
        },
      ],
    },
  },
];

export default config;
