import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillModal. */
export const s = {
  body: { padding: "20px 24px", display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  dropzone: (over: boolean): CSSProperties => ({
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    padding: "36px 20px",
    borderRadius: 10,
    border: "1.5px dashed " + (over ? "var(--accent)" : "var(--border-strong)"),
    background: over ? "var(--accent-bg)" : "var(--bg-surface)",
    cursor: "pointer",
    textAlign: "center",
  }),
  dropIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  dropTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  dropHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  // Visually hidden but focusable; the whole label is the click target.
  fileInput: {
    position: "absolute",
    inset: 0,
    opacity: 0,
    width: "100%",
    height: "100%",
    cursor: "pointer",
  } satisfies CSSProperties,
  error: {
    fontSize: 13,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 7,
    padding: "8px 12px",
  } satisfies CSSProperties,
  trustBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  trustIcon: { flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  sourceLine: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  section: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "10px 12px",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  warningIcon: { color: "var(--warn)", flexShrink: 0 } satisfies CSSProperties,
  ignoredRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 12.5 } satisfies CSSProperties,
  ignoredIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  ignoredPath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  ignoredReason: (danger: boolean): CSSProperties => ({
    fontSize: 12,
    color: danger ? "var(--crit)" : "var(--text-muted)",
    whiteSpace: "nowrap",
  }),
  bodyPanel: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "12px 16px",
    maxHeight: 320,
    overflow: "auto",
    background: "var(--bg-surface)",
    fontSize: 13.5,
  } satisfies CSSProperties,
  raw: { margin: 0, fontSize: 12.5, whiteSpace: "pre-wrap", lineHeight: 1.55 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
} as const;
