import tseslint from "typescript-eslint";
import importPlugin from "eslint-plugin-import";

const config = [
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      // Runtime data: cloned repositories, not source.
      "clones/**",
      // Vendored copy of the shared Zod contracts — owned elsewhere.
      "src/vendor/**",
      // Generated by drizzle-kit; never hand-edited (see AGENTS.md).
      "src/db/migrations/**",
    ],
  },

  ...tseslint.configs.recommended,

  {
    plugins: { import: importPlugin },
    rules: {
      // `_name` marks a binding that is destructured or accepted on purpose
      // but deliberately unused.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],

      /**
       * Module boundaries used to live here as `import/no-restricted-paths`
       * zones (platform/adapters/db ↛ modules) at `warn`, which meant CI never
       * failed on them. They now live in `.dependency-cruiser.cjs` as the full
       * Onion ring ruleset — same three zones plus the ones ESLint could not
       * express: routes ↛ persistence, SQL only in a repository, I/O SDKs only
       * in adapters, no cross-module imports, domain-file purity, and the
       * type-only carve-out that makes "no SQL" checkable at all.
       *
       * They are `error` there, with a committed baseline for the modules that
       * predate the rule, so the tree could go strict without a big-bang
       * refactor. Run `pnpm arch`; `test/architecture.test.ts` runs the same
       * config in the unit lane. Rationale: .claude/skills/onion-architecture/
       *
       * Keep architecture rules in ONE place — two half-overlapping definitions
       * drift, and the drift is invisible until it matters.
       */
    },
  },

  {
    // Tests reach across boundaries on purpose: they wire a module up against
    // a real database and assert on rows.
    files: ["test/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];

export default config;
